<%@ Page Language="C#" MasterPageFile="~/cool cab services/maintenanceManger/MaintenanceManger.master" AutoEventWireup="true" CodeFile="ViewSparePartDetails.aspx.cs" Inherits="maintenanceManger_ViewSparePartDetails" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


    <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
         <tr>
            <td align="center" class="border" colspan="3" >
                <b class="title">SparePartDetails</b></td>
           
            
        </tr>
        <tr>
            <td  align="center">
                <asp:Label ID="LblMSg" runat="server" Text="Label"></asp:Label>
            </td>
        </tr>
        <tr>
            <td  align="center">
                <asp:GridView ID="GdV_SparePart" runat="server" Style="position: static" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" OnRowCommand="GdV_SparePart_RowCommand" OnRowDeleting="GdV_SparePart_RowDeleting" Font-Names="Arial" Font-Size="9pt" AllowPaging="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnPageIndexChanging="GdV_SparePart_PageIndexChanging">
                    <Columns>
                        
                        <asp:TemplateField>
                        <ItemTemplate>
                        <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"SparerPartID") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="SparerPartID" HeaderText="SparerPartID" />
                        <asp:BoundField DataField="DealerName" HeaderText="DealerName" />
                        <asp:BoundField DataField="SparePartType" HeaderText="SparePartType" />
                        <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
                        <asp:BoundField DataField="SparePart" HeaderText="SparePart" />
                        <asp:BoundField DataField="DateOfPurchase" HeaderText="DateOfPurchase" />
                        <asp:BoundField DataField="Price" HeaderText="Price" />
                        <asp:BoundField DataField="AmountPaid" HeaderText="AmountPaid" />
                    </Columns>
                    <RowStyle HorizontalAlign="Center" BackColor="#EFF3FB" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#2461BF" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
            </td>
            <td></td>
        </tr>
        <tr>
            <td align="center">
               
            </td>
            <td>
            </td>
        </tr>
    </table>
</asp:Content>

