<%@ Page Language="C#" MasterPageFile="~/cool cab services/maintenanceManger/MaintenanceManger.master" AutoEventWireup="true" CodeFile="ViewSparePartBilling.aspx.cs" Inherits="maintenanceManger_ViewSparePartBilling" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
   <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
         <tr>
            <td align="center" class="border" colspan="3" >
                <b class="title">View SparePartsDetails</b></td>
           
            
        </tr>
        <tr>
            <td align="center">
                <asp:Label ID="Label1" runat="server" Style="position: static" Text="Label"></asp:Label></td>
        </tr>
        <tr>
            <td  align="center">
                <asp:GridView ID="GdV_sparePart" runat="server" Style="position: static" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowCommand="GdV_sparePart_RowCommand" OnRowDeleting="GdV_sparePart_RowDeleting" AllowPaging="True" Font-Names="Arial" Font-Size="9pt" OnPageIndexChanging="GdV_sparePart_PageIndexChanging">
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                         <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"BillNo") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <RowStyle BackColor="#EFF3FB" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#2461BF" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

