<%@ Page Language="C#" MasterPageFile="~/cool cab services/maintenanceManger/MaintenanceManger.master" AutoEventWireup="true" CodeFile="ViewVehicleDetails.aspx.cs" Inherits="maintenanceManger_ViewVehicleDetails" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

   <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
         <tr>
            <td align="center" class="border" colspan="3" >
                <b class="title">View VehicleDetails</b></td>
           
            
        </tr>
       <tr>
           <td align="center" colspan="3">
               <asp:Label ID="Lbl_ds" runat="server" Text="Label"></asp:Label>
           </td>
       </tr>
        <tr>
            <td  align="center">
                <asp:GridView ID="GdV_Vehicle" runat="server" Style="position: static" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CellPadding="4" Font-Names="Arial" Font-Size="9pt" ForeColor="#333333" GridLines="None" OnRowDeleting="GdV_Vehicle_RowDeleting" OnRowCommand="GdV_Vehicle_RowCommand" AllowPaging="True" OnPageIndexChanging="GdV_Vehicle_PageIndexChanging">
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <RowStyle BackColor="#EFF3FB" />
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"VehicleID") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="VehicleID" HeaderText="VehicleID" />
                        <asp:BoundField DataField="VenderID" HeaderText="VenderID" />
                        <asp:BoundField DataField="DriverID" HeaderText="DriverID" />
                        <asp:BoundField DataField="VehicleType" HeaderText="VehicleType" />
                        <asp:BoundField DataField="RegistorNo" HeaderText="RegistorNo" />
                        <asp:BoundField DataField="RateKm" HeaderText="RateKm" />
                        <asp:BoundField DataField="Capacity" HeaderText="Capacity" />
                        <asp:BoundField DataField="RouteID" HeaderText="RouteID" />
                    </Columns>
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#2461BF" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

