<%@ Page Language="C#" MasterPageFile="~/cool cab services/maintenanceManger/MaintenanceManger.master" AutoEventWireup="true" CodeFile="ViewDriverDetails.aspx.cs" Inherits="maintenanceManger_ViewDriverDetails" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
         <tr>
            <td align="center" class="border" colspan="3" style="height: 22px">
                <b class="title">View DriverDetails</b></td>
           
            
        </tr>
        <tr>
            <td align="center" >
                <asp:Label ID="Label1" runat="server" Style="position: static"></asp:Label>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" Style="position: static" AutoGenerateColumns="False" Font-Names="Arial" Font-Size="9pt" OnRowDeleting="GridView1_RowDeleting" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowCommand="GridView1_RowCommand" AllowPaging="True" OnPageIndexChanging="GridView1_PageIndexChanging">
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="LinkButton2" runat="server" CommandName="View" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"DriverID") %>'>View</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"DriverID") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        
                        </asp:TemplateField>
                        <asp:BoundField DataField="DriverID" HeaderText="DriverID" />
                        <asp:BoundField DataField="Name" HeaderText="DriverName" />
                        <asp:BoundField DataField="Address" HeaderText="Address" />
                        <asp:BoundField DataField="PhoneNo" HeaderText="PhoneNumber" />
                        <asp:BoundField DataField="DOB" HeaderText="DOB" />
                        <asp:BoundField DataField="Experience" HeaderText="Experience" />
                        <asp:BoundField DataField="LicenceNo" HeaderText="LicenceNumber" />
                    </Columns>
                    <RowStyle HorizontalAlign="Center" BackColor="#EFF3FB" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#2461BF" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

