<%@ Page Language="C#" MasterPageFile="~/cool cab services/maintenanceManger/MaintenanceManger.master" AutoEventWireup="true" CodeFile="ViewVendordetails.aspx.cs" Inherits="maintenanceManger_ViewVendordetails" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<br />
<br />
<br />
    <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
         <tr>
            <td align="center" class="border" colspan="3" style="height: 22px">
                <b class="title">View VendorDetails</b></td>
           
            
        </tr>
        <tr>
            <td align="center" >
                <asp:GridView ID="GdV_Vendor" runat="server" Style="position: static" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnPageIndexChanging="GdV_Vendor_PageIndexChanging" PageSize="6" Width="583px" OnRowCommand="GdV_Vendor_RowCommand" OnRowDeleting="GdV_Vendor_RowDeleting">
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit"  CommandArgument='<%#DataBinder.Eval(Container.DataItem,"VenderID") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="VenderID" HeaderText="VendorID" />
                        <asp:BoundField DataField="VenderName" HeaderText="VenderName" />
                        <asp:BoundField DataField="Address" HeaderText="Address" />
                        <asp:BoundField DataField="PhoneNo" HeaderText="PhoneNo" />
                        <asp:BoundField DataField="EmailID" HeaderText="EmailID" />
                        <asp:BoundField DataField="Remarks" HeaderText="Remarks" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

