<%@ Page Language="C#" MasterPageFile="~/cool cab services/QulityAssranceManger/MasterPage.master" AutoEventWireup="true" CodeFile="View FeedBack.aspx.cs" Inherits="FinancialHomePage_View_FeedBack" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


    <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
        <tr>
            <td align="center" class="border" colspan="3">
                <b class="title">View FeedBack</b></td>
           
            
        </tr>
        <tr>
            <td >
            </td>
        </tr>
        <tr>
            <td align="center" >
                <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" Style="position: static" AllowPaging="True" OnPageIndexChanging="GridView1_PageIndexChanging">
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

