<%@ Page Language="C#" MasterPageFile="~/cool cab services/QulityAssranceManger/MasterPage.master" AutoEventWireup="true" CodeFile="View AcciDentDetails.aspx.cs" Inherits="FinancialHomePage_View_AcciDentDetails" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


   <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
        <tr>
            <td align="center" class="border" colspan="3">
                <b class="title">View Accident Details</b></td>
           
            
        </tr>
        <tr>
            <td >
            </td>
        </tr>
        <tr>
            <td  align="center">
                <asp:GridView ID="GrdVAccident" runat="server" Style="position: static" AutoGenerateDeleteButton="True" OnRowDeleting="GrdVAccident_RowDeleting" CellPadding="4" ForeColor="#333333" GridLines="None" Width="385px" AllowPaging="True" Font-Names="Arial" Font-Size="9pt" OnPageIndexChanging="GrdVAccident_PageIndexChanging">
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <RowStyle BackColor="#EFF3FB" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#2461BF" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

