<%@ Page Language="C#" MasterPageFile="~/cool cab services/MovementHomePage/MasterPage.master" AutoEventWireup="true"
    CodeFile="ViewDriverShiftDetails.aspx.cs" Inherits="MovementHomePage_ViewDriverShiftDetails"
    Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">

    <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
        <tr>
            <td align="center" class="border" colspan="3">
                <b class="title">View Driver ShiftDetails</b></td>
        </tr>
        <tr>
            <td align="center">
                <asp:Label ID="LblMSG" runat="server" Style="position: static" Text="Label"></asp:Label></td>
        </tr>
        <tr>
            <td align="center">
                <asp:GridView ID="GdVDriverShiftDetails" runat="server" Style="position: static" AutoGenerateDeleteButton="True" Font-Names="Arial" Font-Size="9pt" OnRowCommand="GdVDriverShiftDetails_RowCommand" OnRowDeleting="GdVDriverShiftDetails_RowDeleting" AllowPaging="True" OnPageIndexChanging="GdVDriverShiftDetails_PageIndexChanging" Width="404px" AutoGenerateColumns="False" PageSize="7">
                    <Columns>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"DriverShiftID") %>'>Edit</asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="DriverShiftID" HeaderText="DriverShiftID" />
                        <asp:BoundField DataField="Name" HeaderText="DriverName" />
                        <asp:BoundField DataField="DriverID" HeaderText="DriverID" />
                        <asp:BoundField DataField="ShiftID" HeaderText="ShiftID" />
                        <asp:BoundField DataField="ShiftDate" HeaderText="ShiftDate" />
                        <asp:BoundField DataField="Shifting" HeaderText="Shifting" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>
