<%@ Page Language="C#" MasterPageFile="~/cool cab services/MovementHomePage/MasterPage.master" AutoEventWireup="true" CodeFile="ViewVehicleAllocation.aspx.cs" Inherits="MovementHomePage_ViewVehicleAllocation" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

   <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
        <tr>
            <td align="center" class="border" colspan="3">
                <b class="title">View VehicleAlloctionDetails</b></td>
        </tr>
        <tr>
            <td  align="center">
                <asp:Label ID="Label1" runat="server" Style="position: static" Text="Label"></asp:Label></td>
        </tr>
        <tr>
            <td  align="center">
                <asp:GridView ID="GridView1" runat="server" Style="position: static" AutoGenerateDeleteButton="True" AllowPaging="True" Font-Names="Arial" Font-Size="9pt" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowCommand="GridView1_RowCommand" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="False">
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                        <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"VehicleAllocationID") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="VehicleAllocationID" HeaderText="VehicleAllocationID" />
                        <asp:BoundField DataField="VehicleID" HeaderText="VehicleID" />
                        <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" />
                        <asp:BoundField DataField="DriverID" HeaderText="DriverID" />
                        <asp:BoundField DataField="PickupDrop" HeaderText="PickupDrop" />
                        <asp:BoundField DataField="RouteID" HeaderText="RouteID" />
                        <asp:BoundField DataField="VDate" HeaderText="VDate" />
                    </Columns>
                    <RowStyle HorizontalAlign="Center" />
                </asp:GridView>
                &nbsp;<asp:Button ID="Button1" runat="server" Style="position: static" Text="Print" OnClick="Button1_Click1" CssClass="button" />
            </td>
        </tr>
    </table>
</asp:Content>

