<%@ Page Language="C#" MasterPageFile="~/cool cab services/MovementHomePage/MasterPage.master" AutoEventWireup="true" CodeFile="ViewRouteDetails.aspx.cs" Inherits="MovementHomePage_ViewRouteDetails" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

   <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
        <tr>
            <td align="center" class="border" colspan="3">
                <b class="title">View RouteDetails</b></td>
        </tr>
        <tr>
            <td align="center">
                <asp:Label ID="LblMSG" runat="server" Style="position: static" Text="Label"></asp:Label></td>
        </tr>
        <tr>
            <td align="center">
                <asp:GridView ID="GdVRoute" runat="server" Style="position: static" 
                    AutoGenerateDeleteButton="True" Font-Names="Arial" Font-Size="9pt" 
                    OnRowCommand="GdVRoute_RowCommand" OnRowDeleting="GdVRoute_RowDeleting" 
                    Width="452px" AllowPaging="True" 
                    OnPageIndexChanging="GdVRoute_PageIndexChanging" AutoGenerateColumns="False" 
                    onselectedindexchanged="GdVRoute_SelectedIndexChanged">
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                         <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"RouteID") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="RouteID" HeaderText="RouteID" />
                        <asp:BoundField DataField="RouteDescription" HeaderText="RouteDescription" />
                        <asp:BoundField DataField="Source" HeaderText="Source" />
                        <asp:BoundField DataField="Destination" HeaderText="Destination" />
                    </Columns>
                    <RowStyle HorizontalAlign="Center" />
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

