<%@ Page Language="C#" MasterPageFile="~/cool cab services/MovementHomePage/MasterPage.master" AutoEventWireup="true" CodeFile="ViewTripSheet.aspx.cs" Inherits="MovementHomePage_ViewTripSheet" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
        <tr>
            <td align="center" class="border" colspan="3">
                <b class="title">View TripSheet Details</b></td>
        </tr>
        <tr>
            <td align="center" >
                <asp:Label ID="Label1" runat="server" Style="position: static" Text="Label"></asp:Label></td>
        </tr>
        <tr>
            <td align="center" >
                <asp:GridView ID="GdVTripSheet" runat="server" Style="position: static" AllowPaging="True" AutoGenerateDeleteButton="True" Font-Names="Arial" Font-Size="9pt" OnRowCommand="GdVTripSheet_RowCommand" OnRowDeleting="GdVTripSheet_RowDeleting" Width="248px" AutoGenerateColumns="False" OnPageIndexChanging="GdVTripSheet_PageIndexChanging">
                    <RowStyle HorizontalAlign="Center" />
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                        <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"TripSheetID") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="TripSheetID" HeaderText="TripSheetID" />
                        <asp:BoundField DataField="AllocationID" HeaderText="AllocationID" />
                        <asp:BoundField DataField="VehicleID" HeaderText="VehicleID" />
                        <asp:BoundField DataField="RateKM" HeaderText="RateKM" />
                        <asp:BoundField DataField="KM" HeaderText="KM" />
                        <asp:BoundField DataField="TotalAmount" HeaderText="TotalAmount" />
                        <asp:BoundField DataField="Remark" HeaderText="Remark" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

